// 定数定義

export const API_CONFIG = {
  TIMEOUT: 180000, // 3分
  MAX_RETRIES: 3,
  MAX_PROMPT_LENGTH: 10000,
  DEFAULT_MODEL: 'claude-3-sonnet-20240229',
} as const;

export const RATE_LIMITS = {
  WINDOW_MS: parseInt(process.env.RATE_LIMIT_WINDOW_MS || '60000'),
  MAX_REQUESTS: parseInt(process.env.RATE_LIMIT_MAX_REQUESTS || '60'),
  SKIP_SUCCESS: process.env.RATE_LIMIT_SKIP_SUCCESS === 'true',
} as const;

export const SECURITY = {
  ALLOWED_ORIGINS: (process.env.ALLOWED_ORIGINS || 'https://script.google.com').split(','),
  CORS_CREDENTIALS: process.env.CORS_CREDENTIALS === 'true',
  API_SECRET: process.env.VERCEL_API_SECRET || '',
} as const;

export const CLAUDE_CONFIG = {
  AUTH_METHOD: process.env.CLAUDE_AUTH_METHOD || 'subscription',
  MODEL: process.env.CLAUDE_MODEL || API_CONFIG.DEFAULT_MODEL,
  TIMEOUT: API_CONFIG.TIMEOUT,
  MAX_RETRIES: API_CONFIG.MAX_RETRIES,
} as const;

export const ERROR_CODES = {
  // 認証エラー
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_API_KEY: 'INVALID_API_KEY',

  // レート制限
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // リクエストエラー
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_PROMPT: 'MISSING_PROMPT',
  PROMPT_TOO_LONG: 'PROMPT_TOO_LONG',

  // Claude関連エラー
  CLAUDE_AUTH_FAILED: 'CLAUDE_AUTH_FAILED',
  CLAUDE_EXECUTION_FAILED: 'CLAUDE_EXECUTION_FAILED',
  CLAUDE_TIMEOUT: 'CLAUDE_TIMEOUT',

  // システムエラー
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;